name: Deploy and release
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-16.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Deploy the project
        run: echo "No deployment target"

  release:
    name: Release
    runs-on: ubuntu-16.04
    needs: deploy
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Release the project
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
